// lib/verticals/data/index.ts — GENERATED by scripts/verticals-registry.mjs. Do not edit.
// Re-run `node scripts/verticals-registry.mjs` after adding, renaming or removing a config.
// Order = file name order (deterministic); hub and nav order is decided in lib/verticals/index.ts.
import type { VerticalConfig } from "../types";
import { aiAutomationAgencies } from "./ai-automation-agencies";
import { aiStartups } from "./ai-startups";
import { brandingAgencies } from "./branding-agencies";
import { cloudConsultancies } from "./cloud-consultancies";
import { consultants } from "./consultants";
import { corporateTrainingCompanies } from "./corporate-training-companies";
import { cybersecurityFirms } from "./cybersecurity-firms";
import { dataConsultancies } from "./data-consultancies";
import { developerTools } from "./developer-tools";
import { eventAgencies } from "./event-agencies";
import { executiveCoaches } from "./executive-coaches";
import { executiveSearchFirms } from "./executive-search-firms";
import { fintechStartups } from "./fintech-startups";
import { fractionalCfos } from "./fractional-cfos";
import { fractionalCmos } from "./fractional-cmos";
import { gtmAgencies } from "./gtm-agencies";
import { healthtechStartups } from "./healthtech-startups";
import { hrConsultants } from "./hr-consultants";
import { hrTechStartups } from "./hr-tech-startups";
import { industrialTechStartups } from "./industrial-tech-startups";
import { legalTechStartups } from "./legal-tech-startups";
import { logisticsTechStartups } from "./logistics-tech-startups";
import { marketingAgencies } from "./marketing-agencies";
import { martechStartups } from "./martech-startups";
import { msps } from "./msps";
import { ppcAgencies } from "./ppc-agencies";
import { prFirms } from "./pr-firms";
import { recruitingAgencies } from "./recruiting-agencies";
import { retailTechStartups } from "./retail-tech-startups";
import { revopsConsultants } from "./revops-consultants";
import { saasStartups } from "./saas-startups";
import { seoAgencies } from "./seo-agencies";
import { shopifyAgencies } from "./shopify-agencies";
import { softwareDevelopmentAgencies } from "./software-development-agencies";
import { solarCompanies } from "./solar-companies";
import { solopreneurs } from "./solopreneurs";
import { sustainabilityConsultants } from "./sustainability-consultants";
import { uxDesignAgencies } from "./ux-design-agencies";
import { videoProductionCompanies } from "./video-production-companies";
import { webDesignAgencies } from "./web-design-agencies";

export const ALL_VERTICALS: VerticalConfig[] = [
  aiAutomationAgencies,
  aiStartups,
  brandingAgencies,
  cloudConsultancies,
  consultants,
  corporateTrainingCompanies,
  cybersecurityFirms,
  dataConsultancies,
  developerTools,
  eventAgencies,
  executiveCoaches,
  executiveSearchFirms,
  fintechStartups,
  fractionalCfos,
  fractionalCmos,
  gtmAgencies,
  healthtechStartups,
  hrConsultants,
  hrTechStartups,
  industrialTechStartups,
  legalTechStartups,
  logisticsTechStartups,
  marketingAgencies,
  martechStartups,
  msps,
  ppcAgencies,
  prFirms,
  recruitingAgencies,
  retailTechStartups,
  revopsConsultants,
  saasStartups,
  seoAgencies,
  shopifyAgencies,
  softwareDevelopmentAgencies,
  solarCompanies,
  solopreneurs,
  sustainabilityConsultants,
  uxDesignAgencies,
  videoProductionCompanies,
  webDesignAgencies,
];
